[package]
name = "grilme99/playfab-example"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabClient = "grilme99/playfab-client@1.220926.0"
PlayFabMatchmaker = "grilme99/playfab-matchmaker@1.220926.0"
