[package]
name = "grilme99/playfab-client"
description = "APIs which provide the full range of PlayFab features available to the client - authentication, account and data management, inventory, friends, matchmaking, reporting, and platform-specific functionality. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220926.6"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
