[package]
name = "grilme99/playfab-insights"
description = "Manage the Insights performance level and data storage retention settings.. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220926.5"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
