[package]
name = "grilme99/playfab-localization"
description = "The Localization APIs give you the tools needed to manage language setup in your title.. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220926.1"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
