[package]
name = "grilme99/playfab-matchmaker"
description = "Enables the use of an external match-making service in conjunction with PlayFab hosted Game Server instances. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220926.5"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
