[package]
name = "grilme99/playfab-economy"
description = "API methods for managing the catalog. Inventory manages in-game assets for any given entity.. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.221024.0"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
