[package]
name = "grilme99/playfab-experimentation"
description = "APIs for managing experiments.. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.220926.4"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
