[package]
name = "grilme99/playfab-internal"
description = "Internal package for making API calls and managing PlayFab settings. Do not consume directly."
version = "1.0.1"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
