[package]
name = "grilme99/playfab-leaderboards"
description = "Manage entity statistics Manage entity statistics. For more info, see: https://github.com/grilme99/RobloxPlayFabSDK"
version = "1.221010.1"
license = "MIT"
authors = ["Brooke Rhodes <brooke@gril.me>"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
PlayFabInternal = "grilme99/playfab-internal@^1"
